class COMMAND:
    CMD_MOTORS_ON = "CMD_SERVOPOWER#1"
    CMD_MOTORS_OFF = "CMD_SERVOPOWER#0"
    CMD_BUZZER_ON = "CMD_BUZZER#1"
    CMD_BUZZER_OFF = "CMD_BUZZER#0"
    CMD_ULTRASONIC = "CMD_SONIC"

    CMD_MOVE = "CMD_MOVE"
    CMD_LED_MOD = "CMD_LED_MOD"
    CMD_LED = "CMD_LED"
    CMD_HEAD = "CMD_HEAD"
    CMD_BALANCE = "CMD_BALANCE"
    CMD_ATTITUDE = "CMD_ATTITUDE"
    CMD_POSITION = "CMD_POSITION"
    CMD_RELAX = "CMD_RELAX"
    CMD_POWER = "CMD_POWER"
    CMD_CALIBRATION = "CMD_CALIBRATION"
    CMD_CAMERA = "CMD_CAMERA"

    def __init__(self):
        pass
